import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

function header() {
    return (
        <Head>
            <title>Dheeraj Verma | Full Stack Developer, Android Developer</title>
            <meta name="description" content="Generated by create next app" />
            <Link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default header
